### ISSUE TITLE
Exception being thrown in Extension Deactivate

### ISSUE THREAD

**Issue by ashgti** [bazel-contrib/vscode-bazel#245]
In the 0.4.1 release, if a folder is converted into a workspace then the bazel extension ends up throwing an error from `BuildifierDiagnosticsManager.dispose` saying `this.disposables is not iterable`.

```
[2021-08-20 10:33:34.862] [exthost] [error] TypeError: this.disposables is not iterable
	at BuildifierDiagnosticsManager.dispose (/Users/harjohn/.vscode/extensions/bazelbuild.vscode-bazel-0.4.1/out/src/buildifier/buildifier_diagnostics_manager.js:85:39)
	at l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:14:4943)
	at v._deactivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11421)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:10000
	at Array.map (<anonymous>)
	at v.deactivateAll (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9988)
	at P.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:725)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:32088)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:29731)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
```

**Comment by ashgti** [comment]
https://github.com/bazelbuild/vscode-bazel/blob/12c20773c5bbbdbbd30cc393c414622059c05537/src/buildifier/buildifier_diagnostics_manager.ts#L35 is uninitialized.

**Comment by cbandera** [comment]
Fixed in #487. See https://github.com/bazel-contrib/vscode-bazel/pull/487/changes#diff-a1b0f963d9bae6863682b13b8d85dd6c616f5406f17d425e9c5ae13b52382ed5
